### ISSUE TITLE
BUG: Subject doesn't appears after the student do the enrollment

### ISSUE THREAD

**Issue by davixcky** [Cronun/cronun#13]
Hi Cronun team. I wanna appreciate for all the effort that you are doing. This was the first time that I have to do an enrollment and with this tool, was really easy and smooth. 

The bug if we can call this like that, it's basically generated after you do the enrollment in aurora. 

## What I want to see my favorites if I already do the enrollment? 
It's not the big deal (maybe also without sense), but sometimes you want to see how many slots are missing or you wanna make some changes in your schedule.

![Screenshot from 2021-01-19 11-44-06](https://user-images.githubusercontent.com/34346877/105066025-875d8700-5a4c-11eb-9361-e20d2d44811c.png)

**Comment by krthr** [comment]
Hello, @davixcky . Thank you!

The problem you are referring to has to do with the blank favorite schedules?

**Comment by davixcky** [comment]
Yeah, exactly

**Comment by krthr** [comment]
I think this error occurs when a saved schedule is no longer valid: a group is full or no longer exists, etc. I think @rmacuna  was working on a notification for the user when it happens.

By the way, we're glad you were able to use the application.
